version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: redis:alpine
    ports:
      - "6378:6379"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - funzone-sqlserver:/var/opt/mssql
  
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5339:80"

  aggregator:
    image: ${REGISTRY:-funzone}/aggregator
    build:
      context: .
      dockerfile: src/ApiGateways/Funzone.Aggregator/Dockerfile
    ports:
      - "5201:80"
    depends_on:
      - identity-api
      - albums-api
  
  aggregator-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", 
    "-app-id", "aggregator", 
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/funzone-config.yaml"]
    depends_on:
      - aggregator
    network_mode: "service:aggregator"
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  identity-api:
    image: ${REGISTRY:-funzone}/identity.api
    build:
      context: .
      dockerfile: src/Services/Identity/Funzone.Services.Identity.Api/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5203:80"
  
  identity-api-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd",
    "-app-id", "identity-api",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/funzone-config.yaml"]
    depends_on:
      - identity-api
    network_mode: "service:identity-api"
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  albums-api:
    image: ${REGISTRY:-funzone}/albums.api
    build:
      context: .
      dockerfile: src/Services/Albums/Funzone.Services.Albums.Api/Dockerfile
    ports:
      - "5204:80"

  albums-api-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd",
    "-app-id", "albums-api",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/funzone-config.yaml"]
    depends_on:
      - albums-api
    network_mode: "service:albums-api"
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

volumes:
  funzone-sqlserver: {}