version: '3.4'

services:
  aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  albums-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"