name: albums-api

on:
  push:
    branches:
    - main
    
    paths:
    - src/BuildingBlocks/**
    - src/Services/Albums/**
    - .github/workflows/albums-api.yml
    
  pull_request:
    branches:
    - main
    
    paths:
    - src/BuildingBlocks/**
    - src/Services/Albums/**
    - .github/workflows/albums-api.yml

env:
  SERVICE: albums-api
  IMAGE: albums.api

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    
    - name: Compose build ${{ env.SERVICE }}
      run: sudo -E docker-compose build ${{ env.SERVICE }}
      working-directory: ./
      shell: bash
      env:
        TAG: ${{ env.BRANCH }}
        REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}