name: build and test

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  
  build:
    name: Build and run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
          
      - name: Install dependencies
        run: dotnet restore Funzone.sln
        working-directory: .
        
      - name: Build solution
        run: dotnet build Funzone.sln --configuration Release --no-restore
        working-directory: .

      - name: Run Identity Unit Tests
        run: dotnet test --configuration Release --no-build --verbosity minimal ./src/Services/Identity/Tests/Funzone.Services.Identity.UnitTests/Funzone.Services.Identity.UnitTests.csproj
        working-directory: .
        
      - name: Run Album Unit Tests
        run: dotnet test --configuration Release --no-build --verbosity minimal ./src/Services/Albums/Tests/Funzone.Services.Albums.UnitTests/Funzone.Services.Albums.UnitTests.csproj
        working-directory: .
        
  integration:
    name: Build and run integration tests
    needs: [build]
    runs-on: ubuntu-latest
    services: 
      sqlserver-db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: 112ssD@wrd
        ports:
          - 1433:1433
        options: --name sqltest
        
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101

      - name: Install dependencies
        run: dotnet restore Funzone.sln
        working-directory: .

      - name: Build solution
        run: dotnet build Funzone.sln --configuration Release --no-restore
        working-directory: .

      - name: Run Identity Integration Tests
        run: dotnet test --configuration Release --no-build --verbosity minimal ./src/Services/Identity/Tests/Funzone.Services.Identity.IntegrationTests/Funzone.Services.Identity.IntegrationTests.csproj
        working-directory: .
        
      - name: Run Album Integration Tests
        run: dotnet test --configuration Release --no-build --verbosity minimal ./src/Services/Albums/Tests/Funzone.Services.Albums.IntegrationTests/Funzone.Services.Albums.IntegrationTests.csproj
        working-directory: .