name: continuous integration

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
          
      - name: Install dependencies
        run: dotnet restore Funzone.sln
        working-directory: .
        
      - name: Build solution
        run: dotnet build Funzone.sln --configuration Release --no-restore
        working-directory: .
        
      - name: Run Unit Tests
        run: dotnet test Funzone.sln --configuration Release --no-build --verbosity minimal --filter UnitTests
        working-directory: ./src