name: identityaccess-api

on:
  push:
    branches:
    - main
    
    paths:
    - src/BuildingBlocks/**
    - src/IdentityAccess/**
    - .github/workflows/identityaccess-api.yml
    
  pull_request:
    branches:
    - main
    
    paths:
    - src/BuildingBlocks/**
    - src/IdentityAccess/**
    - .github/workflows/identityaccess-api.yml

env:
  SERVICE: identityaccess-api
  IMAGE: identityaccess.api

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    
    - name: Enable experimental features for the Docker daemon and CLI
      run: |
          echo $'{\n  "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          mkdir -p ~/.docker
          echo $'{\n  "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
          sudo service docker restart
          docker version -f '{{.Client.Experimental}}'
          docker version -f '{{.Server.Experimental}}'

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}